### ISSUE TITLE
Add idx tags

### ISSUE THREAD

**Issue by mitchkeller** [mitchkeller/pretext-basics-reference#1]
I have thrown in an assortment of `idx` tags to show the sorts of things that I think should be added consistently and comprehensively. Remove `idx` tags with great caution, but add them liberally.

If working on this issue during the PTX in PDX workshop, please add a comment here indicating which chapters you've claimed to work on.

**Comment by mattboelkins** [comment]
I'm doing Chapter 4 - Mathematics

**Comment by mattboelkins** [comment]
I've done Chapter 4 and will now do Chapter 5 - Lists

**Comment by jjrsylvestre** [comment]
Working on Chapter 6: Theorem-like elements

**Comment by mattboelkins** [comment]
Working on Chapter 7:  Examples

**Comment by mattboelkins** [comment]
Will work on Chapter 10: Exercises, too

**Comment by jjrsylvestre** [comment]
Chapters 8 & 9 (Remark-like elements and Project-like elements) are now indexed in a pull request.

**Comment by mattboelkins** [comment]
I'll take project-like (chapter 9, already initially indexed by Jeremy, but will update in light of the read-me and "theorem-like" and "example-like"), and then I'll take 11 & 12.

**Comment by oscarlevin** [comment]
I'll work on remark-like (ch 8, building on Jeremy's work) and then start on 17 & 16 (and work backwards).

**Comment by mitchkeller** [comment]
I'll start with 13 and 14, since 14 needs some revising to use `title` instead of `caption`.

**Comment by mitchkeller** [comment]
I think we're almost there. I finished 13 and 14 and then moved on to 11 and cleaned up 3, 4, and 5 to be consistent with the new standards. It appears that 10, 12, and 15 remain. Would @mattboelkins have time to do 10 and 12 and @oscarlevin to do 15?

**Comment by oscarlevin** [comment]
Yes,  I will do ch 15.

**Comment by mattboelkins** [comment]
And I'll do 10 and 12.

**Comment by mitchkeller** [comment]
Good teamwork, guys. I have proofread the index and think things are now as consistent as they're going to get.
