### ISSUE TITLE
index knowls not populating

### ISSUE THREAD

**Issue by mattboelkins** [mitchkeller/pretext-basics-reference#14]
The links to chapters work, but links to listings or paragraphs don't seem to show.  I can see the knowl html files in the appropriate output folder.  See below screenshot.

<img width="1077" alt="index-knowls" src="https://user-images.githubusercontent.com/13908005/61285072-394c3100-a78e-11e9-881d-913f5ca61012.png">

**Comment by mitchkeller** [comment]
This applies to knowls in other contexts, too. I'm not sure if it's a result of excerpting the full guide or something else. Will track this down later.

**Comment by mitchkeller** [comment]
Ugh. The latest Firefox no longer shows local knowls. I'm going to close this. Going forward, development will require following the [instructions in the Author's Guide](https://pretextbook.org/doc/author-guide/html/processing-testing-html.html). Make sure to run the command from in the `output/html` directory. To kill the simple web server, use control+C. (I would use a tab or terminal window just for launching the little web server.)
